Fixed STEAMUSER_HOME in util/steambox launcher
rsharo/steamos_docker pull request #8
Opened 2017-01-19 11:40 UTC by jcorrado

My Debian Jessie (8.7) with upstream 1.13.0-0 docker-engine package will not start a container with a volume specified with `~user' syntax - it requires a full path.

2017-01-19 11:42 UTC, jcorrado commented
And thank you for building this!  Really nice work.

2017-01-21 17:54 UTC, rsharo commented
Hi @jcorrado ,

Thanks for the PR and interest in the project!

Comments on the diffs below...

2017-01-21 18:05 UTC, rsharo requested changes
Only one change requested...

Would like README.md to say something like:
`export STEAMUSER_HOME=`*&lt;your home directory&gt;*
or:
`export STEAMUSER_HOME=$(grep "^${USER}" /etc/passwd | cut -f6 -d:)`

Or alternately something else that avoids using the `$HOME` variable directly.

2017-01-21 18:05 UTC, rsharo commented on README.md
> +export STEAMUSER_HOME=${HOME}
@jcorrado This change has security implications. Some people will choose to run these build scripts as root -- this would cause all their steam files to go to `/root` if they did this.  This is the reason for all the `${USER}` garbage in here.

I'm still working on a solution, but I can offer this alternative if tilde-notation doesn't work on your system:
```
export STEAMUSER_HOME=$(grep "${USER}" /etc/passwd | cut -f6 -d:)
```
or alternately, just type the path to your (user account) home directory directly.
```
export STEAMUSER_HOME=/home/myaccountname
```

Still pondering how to simplify/automate these things.  In the mean time, feel free to submit a suggested `README.md` change.

2017-01-21 18:05 UTC, rsharo commented on util/steambox
> +echo STEAMUSER_HOME=${STEAMUSER_HOME:?"$0: you must set the environment variable STEAMUSER_HOME"}
@jcorrado Yup. This is definitely a bug. Will be accepting this one.

2017-01-21 18:05 UTC, rsharo commented on util/steambox
> +	-v "${STEAMUSER_HOME}/.pulse:/home/steamuser/.pulse"
@jcorrado Also a bug. Good catch!  Will be accepting.

2017-01-21 18:11 UTC, rsharo commented
@jcorrado Or if you approve, I could accept the PR as-is and then clarify the readme.  Please let me know your preference.

2017-01-22 01:03 UTC, jcorrado commented
Hi @rsharo,

Let me rework this PR to address the point you raised about root and the use of `$HOME'.  I should have time for that tomorrow.


Thanks,
Jereme

2017-01-22 01:03 UTC, closed without merging

2017-01-24 13:09 UTC, jcorrado commented on README.md
> +export STEAMUSER_HOME=${HOME}
@rsharo, I think the user of `$USER' also suffers from the same good point you raised about `$HOME'.  What is your thinking here?  I've been going back and forth on the README rewrite, trying to keep things simple, without explicitly encouraging an abbreviated setup that builds a container tightly connected to the local root account.  I think a good intention would be to encourage building a container suitable to be run in the context of the user's normal X session.

Such a trivial doc change has been harder than I expected!  Please let me know your thoughts as I'd like to get this PR over to you.

2017-01-24 13:12 UTC, jcorrado commented on README.md
> +export STEAMUSER_HOME=${HOME}
Something like this is where I'm at now, though it feels a bit muddled
> **[TL;DR]**  From an account with Docker privileges (e.g. root), run the following:
```
XUSER=<the user account you log into X with>
export STEAMUSER_UID=$(id -u ${XUSER})
export STEAMUSER_GID=$(id -g ${XUSER})
export STEAMUSER_HOME=$(grep "${XUSER}" /etc/passwd | cut -f6 -d:)
mkdir $STEAMUSER_HOME/steamhome && chown ${XUSER}:${XUSER} ${XUSER}/steamhome
make
util/steambox
```